#!/usr/bin/env bash
# utilities/bash/maas-state-cache.sh
#
# Sourceable helper for reading the MaaS state snapshot.
# The snapshot is generated by scripts/ai-only-scripts/fetch-maas-state/run
# and cached at $_DYNAMIC_DIR/maas-state/maas-state.yaml.
#
# Usage in bash scripts:
#   . "$(_GIT_ROOT)/utilities/bash/maas-state-cache.sh"
#   ensure_maas_state_fresh                    # fetch if stale (uses _MAAS_HOST from env or config)
#   ensure_maas_state_fresh 10.0.10.11 60      # explicit host and TTL
#   maas_state_file                            # echo path to cache file
#   maas_state_get_status  "ms01-01"           # → "Deployed"
#   maas_state_get_field   "ms01-01" power_type  # → "amt"
#   maas_state_find_sysid  "ms01-01"           # → "abc123"
#   maas_state_get_probes  "ms01-01"           # → YAML block for probes
#   maas_state_all_json                        # → full machines JSON (for jq/Python)
#
# All query functions require ensure_maas_state_fresh to have been called first
# (or the cache file to exist).  They fail fast with a clear message if the
# cache is missing.
#
# Environment variables read:
#   _MAAS_STATE_CACHE_TTL   cache lifetime in seconds (default: 120)
#   _DYNAMIC_DIR            set by set_env.sh
#   _GIT_ROOT               set by set_env.sh (or git rev-parse --show-toplevel)

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

_maas_state_git_root() {
    if [[ -n "${_GIT_ROOT:-}" ]]; then
        echo "$_GIT_ROOT"
    else
        git rev-parse --show-toplevel
    fi
}

_maas_state_dynamic_dir() {
    if [[ -n "${_DYNAMIC_DIR:-}" ]]; then
        echo "$_DYNAMIC_DIR"
    else
        echo "$(_maas_state_git_root)/config/tmp/dynamic"
    fi
}

# ---------------------------------------------------------------------------
# Public: maas_state_file
#   Echo the path to the cache YAML file.
# ---------------------------------------------------------------------------
maas_state_file() {
    echo "$(_maas_state_dynamic_dir)/maas-state/maas-state.yaml"
}

# ---------------------------------------------------------------------------
# Public: ensure_maas_state_fresh [maas_host] [ttl_seconds]
#   Refresh the cache if it is older than ttl_seconds (default: _MAAS_STATE_CACHE_TTL or 120).
#   Calls scripts/ai-only-scripts/fetch-maas-state/run with appropriate flags.
# ---------------------------------------------------------------------------
ensure_maas_state_fresh() {
    local maas_host="${1:-}"
    local ttl="${2:-${_MAAS_STATE_CACHE_TTL:-120}}"
    local cache_file
    cache_file="$(maas_state_file)"
    local fetch_script
    fetch_script="$(_maas_state_git_root)/infra/maas-pkg/_wave_scripts/common/fetch-maas-state/run"

    if [[ ! -f "$fetch_script" ]]; then
        echo "ERROR: fetch-maas-state script not found at $fetch_script" >&2
        return 1
    fi

    local age=999999
    if [[ -f "$cache_file" ]]; then
        local mtime now
        mtime=$(python3 -c "import os; print(int(os.path.getmtime('$cache_file')))" 2>/dev/null || echo 0)
        now=$(python3 -c "import time; print(int(time.time()))" 2>/dev/null || echo 0)
        age=$((now - mtime))
    fi

    if [[ "$age" -lt "$ttl" ]]; then
        return 0  # cache is fresh — caller continues without output noise
    fi

    echo "=== MaaS state cache stale (${age}s old, TTL ${ttl}s) — refreshing ===" >&2
    local args=(--ttl "$ttl")
    [[ -n "$maas_host" ]] && args+=(--out "$(maas_state_file)")  # host override not currently wired; placeholder
    "$fetch_script" "${args[@]}" >&2
}

# ---------------------------------------------------------------------------
# Internal: fail if cache is missing
# ---------------------------------------------------------------------------
_maas_state_require_cache() {
    local f
    f="$(maas_state_file)"
    if [[ ! -f "$f" ]]; then
        echo "ERROR: MaaS state cache not found at $f" >&2
        echo "       Run: scripts/ai-only-scripts/fetch-maas-state/run" >&2
        return 1
    fi
}

# ---------------------------------------------------------------------------
# Internal: run Python query against the cache YAML
# ---------------------------------------------------------------------------
_maas_state_py() {
    _maas_state_require_cache || return 1
    python3 - "$(maas_state_file)" "$@"
}

# ---------------------------------------------------------------------------
# Public: maas_state_get_status <hostname>
#   Echo the status_name for the given hostname.  Returns 1 if not found.
# ---------------------------------------------------------------------------
maas_state_get_status() {
    local hostname="$1"
    _maas_state_py "$hostname" <<'PYEOF'
import sys, yaml
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
hostname = sys.argv[2]
machines = data.get('machines', {})
if hostname not in machines:
    print(f"ERROR: hostname '{hostname}' not in MaaS state cache", file=sys.stderr)
    sys.exit(1)
print(machines[hostname].get('status_name', 'Unknown'))
PYEOF
}

# ---------------------------------------------------------------------------
# Public: maas_state_get_field <hostname> <field>
#   Echo the value of a top-level field for the given hostname.
#   Nested fields are not supported; use maas_state_all_json + jq for those.
# ---------------------------------------------------------------------------
maas_state_get_field() {
    local hostname="$1"
    local field="$2"
    _maas_state_py "$hostname" "$field" <<'PYEOF'
import sys, yaml
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
hostname = sys.argv[2]
field = sys.argv[3]
machines = data.get('machines', {})
if hostname not in machines:
    print(f"ERROR: hostname '{hostname}' not in MaaS state cache", file=sys.stderr)
    sys.exit(1)
val = machines[hostname].get(field)
if val is None:
    sys.exit(0)  # not present — print nothing, exit 0
if isinstance(val, (list, dict)):
    import json
    print(json.dumps(val))
else:
    print(val)
PYEOF
}

# ---------------------------------------------------------------------------
# Public: maas_state_find_sysid <hostname>
#   Echo the MaaS system_id for the given hostname.
# ---------------------------------------------------------------------------
maas_state_find_sysid() {
    maas_state_get_field "$1" system_id
}

# ---------------------------------------------------------------------------
# Public: maas_state_get_probes <hostname>
#   Echo the probes dict as JSON (for inspection or jq queries).
# ---------------------------------------------------------------------------
maas_state_get_probes() {
    maas_state_get_field "$1" probes
}

# ---------------------------------------------------------------------------
# Public: maas_state_all_json
#   Echo the full machines dict as JSON (for jq or Python processing).
# ---------------------------------------------------------------------------
maas_state_all_json() {
    _maas_state_require_cache || return 1
    python3 - "$(maas_state_file)" <<'PYEOF'
import sys, yaml, json
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
print(json.dumps(data.get('machines', {})))
PYEOF
}

# ---------------------------------------------------------------------------
# Public: maas_state_list
#   Print a one-line summary for every machine in the cache.
# ---------------------------------------------------------------------------
maas_state_list() {
    _maas_state_require_cache || return 1
    python3 - "$(maas_state_file)" <<'PYEOF'
import sys, yaml
with open(sys.argv[1]) as f:
    data = yaml.safe_load(f)
machines = data.get('machines', {})
print(f"  {'HOSTNAME':<28}  {'STATUS':<22}  {'POWER_TYPE':<12}  {'IPs'}")
print(f"  {'-'*28}  {'-'*22}  {'-'*12}  {'-'*30}")
for name, m in sorted(machines.items()):
    ips = ', '.join(m.get('ip_addresses', []))
    print(f"  {name:<28}  {m.get('status_name','?'):<22}  {m.get('power_type','?'):<12}  {ips}")
PYEOF
}

# ---------------------------------------------------------------------------
# Public: maas_state_invalidate
#   Remove the cache file so the next ensure_maas_state_fresh call always fetches.
# ---------------------------------------------------------------------------
maas_state_invalidate() {
    local f
    f="$(maas_state_file)"
    if [[ -f "$f" ]]; then
        rm -f "$f"
        echo "MaaS state cache cleared." >&2
    fi
}
