#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
export _FRAMEWORK_PKG_DIR="${_FRAMEWORK_PKG_DIR:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
. "$_FRAMEWORK_PKG_DIR/../../set_env.sh"
. "$_UTILITIES_DIR/bash/init.sh"

export PYTHON_VERSION='python3.12'
_activate_python_locally "$SCRIPT_DIR"

cd "${SCRIPT_DIR}" && exec python3 -m config_mgr.main "$@"
